[project]
name = "ui-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "pandas",
    "scikit-learn",
    # add all your other dependencies here
]
[tool.poetry]
name = "ui-streamlit"
version = "0.1.0"
packages = [{include = "ui_streamlit"}]  # if in project root
# OR
packages = [{include = "ui_streamlit", from = "src"}]  # if in src/
